name: WeekPlans Beta
description: Beta releases of WeekPlans. Digital weekly schedule display for home automation. May be unstable - for testing only.
version: "0.0.0"
slug: weekplans_beta
arch:
  - aarch64
  - amd64
init: false
ports:
  80/tcp: 8080
ingress: true
ingress_port: 80
ingress_entry: /admin
webui: "http://[HOST]:[PORT:80]/admin"
panel_icon: mdi:calendar-week
panel_title: WeekPlans Beta Admin
image: ghcr.io/snowballchris/weekplans:beta
options:
  mqtt_enabled: false
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
schema:
  mqtt_enabled: bool
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
